### PR TITLE
nanosecond fix and additional test cases

### PR DESCRIPTION
**Pull request by ryancox**
I have been doing some work fuzz testing the network parsing code. While doing so, I noticed that I could not round-trip some packets that I captured via wireshark that contained high resolution cdtimes. The byte streams would be off by 1. I tracked this down to the newNano function and division by 1000000000. This forced a round. Since go rounds down, a nanosecond would be lost for non-zero nano-second values. I've added a fix for that as well as some additional test cases.

### CODE REVIEW

**Comment by octo** [comment]
Hi @ryancox, thank you so much for your fixes :) I'm not so sure that simply adding 1 to the nano-second part is doing the right thing, i.e. accounting for rounding errors: essentially it changes the rounding-down behavior to a rounding-up behavior, which doesn't improve the situation imho.

How about adding *5e8* before dividing by *1e9* (and after shifting by 30 bits)? That should round correctly, no?

Best regards,
—octo

**Comment by ryancox** [comment]
@octo I'm certainly open to better solutions. Adding a nano-second for non-zero values seemed to work empirically based on packets i had captured via wireshark as well as dates I created in tests cases.

Gave this a whirl but it's failing my test cases:
```
        s = s << 30

        ns = ns % 1000000000
-       ns = (ns << 30) / 1000000000
-
-       // division by a large number will necessitate a round; go rounds down
-       // and will lose a nanosecond
-       if ns != 0 {
-               ns += 1
-       }
+       ns = ((ns << 30) + 500000000) / 1000000000

        return Time(s | ns)
 }
```

```	
cdtime_test.go:56: got 2009-02-04T21:00:57.099999999-08:00, want 2009-02-04T21:00:57.1-08:00
cdtime_test.go:56: got 2009-02-04T21:00:57.009999999-08:00, want 2009-02-04T21:00:57.01-08:00
cdtime_test.go:56: got 2009-02-04T21:00:57.000099999-08:00, want 2009-02-04T21:00:57.0001-08:00
cdtime_test.go:56: got 2009-02-04T21:00:57.000009999-08:00, want 2009-02-04T21:00:57.00001-08:00
cdtime_test.go:56: got 2009-02-04T21:00:57.000000099-08:00, want 2009-02-04T21:00:57.0000001-08:00
```

**Comment by octo** [comment]
Hi @ryancox,

it turns out that fixing the rounding behaviour works, we just need to do it in both directions, i.e. from ns to cdtime *and* from cdtime to ns / UNIX time. Thanks for discovering and reporting this!

Best regards,
—octo

**Comment by ryancox** [comment]
@octo Super ... and is that compatible with the methodology used in https://github.com/collectd/collectd/blob/master/src/daemon/utils_time.h  ?

**Comment by octo** [comment]
@ryancox it is now :) *collectd* used to take an easy way out by casting to double and doing the multiplication / division then. This was far more imprecise than the off-by-one fixes we've addressed here. The commit mentioned above fixes these issues in *collectd*, too.

**Comment by ryancox** [comment]
super ... btw just realized i had a different email in my .gitconfig .. so these PRs ended up not associated with my github user :( oops ! fixed now

**Pull request merged**
